### ISSUE TITLE
 Redundant setValue  

### ISSUE THREAD

**Issue by santhoshvai** [jherr/no-bs-ts#3]
It seems that the `setValue` in line-32 is redundant. Since the useEffect is adding a subscriber.

https://github.com/jherr/no-bs-ts/blob/82dd7198fd9710765b640bb4fd554a02066749ca/series-2/episode-2-pubsub/state-manager/src/simpleStateManager.ts#L25-L35

Many thanks for the great content on YouTube!

**Comment by jherr** [comment]
Yep. That's true.
