### ISSUE TITLE
Issues with Property 'children'

### ISSUE THREAD

**Issue by DevNinjawork998** [jherr/no-bs-ts#7]
I am facing some issue with regards to the props type for children. 
Looked up in StackOverflow but I am still not sure how to resolve it. 

![image](https://github.com/jherr/no-bs-ts/assets/67252332/49284ebf-ba95-4145-a24d-0061886ae921)
![image](https://github.com/jherr/no-bs-ts/assets/67252332/c41a3485-8991-4604-ade7-80c530183779)

**Comment by jherr** [comment]
This is not an issue with this repository. There is a Discord server associated with the Blue Collar Coder YT channel. Feel free to post this question there but **READ** and **FOLLOW** the #rules of the server **THOROUGHLY** before posting.

**Comment by DevNinjawork998** [comment]
Thanks @jherr, will look into that, cheers!
